---
- name: Generate htpasswd
  block:
    - name: Set username from config or generate if empty
      set_fact:
        username: "{{ basic_auth.username if basic_auth.username | length > 0 else 'user' + lookup('password', '/dev/null chars=ascii_letters,digits length=' + (basic_auth.username_length | int - 4) | string) }}"

    - name: Set password from config or generate if empty
      set_fact:
        password: "{{ basic_auth.password if basic_auth.password | length > 0 else lookup('password', '/dev/null chars=ascii_letters,digits length=' + basic_auth.password_length | string) }}"

    - name: Remove old htpasswd file
      file:
        path: '{{ common.path }}/docker/nginx/auth/htpasswd'
        state: absent

    - name: Install python3-passlib
      apt:
        name: python3-passlib
        state: present

    - name: Generate htpasswd file
      community.general.htpasswd:
        path: '{{ common.path }}/docker/nginx/auth/htpasswd'
        name: "{{ username }}"
        password: "{{ password }}"
        owner: root
        group: root
        mode: 0644

    - name: Generate basic_auth.conf
      copy:
        dest: '{{ common.path }}/docker/nginx/auth/basic_auth.conf'
        content: |
          auth_basic "Registry realm";
          auth_basic_user_file /etc/nginx/auth/htpasswd;
        owner: root
        group: root
        mode: '0644'
  when: basic_auth.enabled | default(false)